import type { AnimationObject } from "lottie-react-native";
import type { Achievement } from "@/api/achievements";

export type StreakTier = "bronze" | "silver" | "gold" | "sapphire" | "amethyst" | "ruby";

/** Generated by `scripts/build-streak-medals.mjs` from the base medal. */
export const MEDAL_SOURCES: Record<StreakTier, AnimationObject> = {
  bronze: require("@assets/animations/medals/bronze.json"),
  silver: require("@assets/animations/medals/silver.json"),
  gold: require("@assets/animations/medals/gold.json"),
  sapphire: require("@assets/animations/medals/sapphire.json"),
  amethyst: require("@assets/animations/medals/amethyst.json"),
  ruby: require("@assets/animations/medals/ruby.json"),
};

/** Streak length → medal colour: 3 bronze, 7 silver, 14 gold, 30 sapphire, 60 amethyst, 100+ ruby. */
export function tierForDays(days: number): StreakTier {
  if (days >= 100) return "ruby";
  if (days >= 60) return "amethyst";
  if (days >= 30) return "sapphire";
  if (days >= 14) return "gold";
  if (days >= 7) return "silver";
  return "bronze";
}

export function isStreakAchievement(achievement: Pick<Achievement, "criteriaType">): boolean {
  return achievement.criteriaType === "STREAK_DAYS";
}
